// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CommentPost struct {
	ID               string `json:"id"`
	Postid           string `json:"postid"`
	Userid           string `json:"userid"`
	Username         string `json:"username"`
	Comment          string `json:"comment"`
	Date             string `json:"date"`
	Replycount       int    `json:"replycount"`
	Likecommentcount int    `json:"likecommentcount"`
}

type CommentReels struct {
	ID       string `json:"id"`
	Reelsid  string `json:"reelsid"`
	Userid   string `json:"userid"`
	Username string `json:"username"`
	Comment  string `json:"comment"`
	Date     string `json:"date"`
}

type Conversation struct {
	ID      string `json:"id"`
	Userid1 string `json:"userid1"`
	Userid2 string `json:"userid2"`
	Date    string `json:"date"`
}

type ConversationHeader struct {
	ID    string `json:"id"`
	User1 *User  `json:"user1"`
	User2 *User  `json:"user2"`
}

type File struct {
	ID        string `json:"id"`
	Groupid   string `json:"groupid"`
	Filename  string `json:"filename"`
	Mediaurl  string `json:"mediaurl"`
	Userid    string `json:"userid"`
	Ownername string `json:"ownername"`
	Date      string `json:"date"`
	Filetype  string `json:"filetype"`
}

type Friend struct {
	ID       string `json:"id"`
	Userid   string `json:"userid"`
	Friendid string `json:"friendid"`
}

type FriendRequests struct {
	ID          string `json:"id"`
	Userid      string `json:"userid"`
	Requesterid string `json:"requesterid"`
}

type Group struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Privacy    string `json:"privacy"`
	Profilepic string `json:"profilepic"`
	Date       string `json:"date"`
}

type GroupHeader struct {
	ID    string `json:"id"`
	Group *Group `json:"group"`
}

type GroupInvited struct {
	ID      string `json:"id"`
	Groupid string `json:"groupid"`
	Userid  string `json:"userid"`
}

type GroupMember struct {
	ID      string `json:"id"`
	Groupid string `json:"groupid"`
	Userid  string `json:"userid"`
	Role    string `json:"role"`
}

type GroupPost struct {
	ID           string `json:"id"`
	Groupid      string `json:"groupid"`
	Groupname    string `json:"groupname"`
	Date         string `json:"date"`
	Text         string `json:"text"`
	Privacy      string `json:"privacy"`
	Commentcount int    `json:"commentcount"`
	Likecount    int    `json:"likecount"`
}

type GroupRequestJoin struct {
	ID      string `json:"id"`
	Groupid string `json:"groupid"`
	Userid  string `json:"userid"`
}

type LikeComment struct {
	ID        string `json:"id"`
	Commentid string `json:"commentid"`
	Userid    string `json:"userid"`
	Username  string `json:"username"`
	IsLike    bool   `json:"isLike"`
}

type LikePost struct {
	ID       string `json:"id"`
	Postid   string `json:"postid"`
	Userid   string `json:"userid"`
	Username string `json:"username"`
	IsLike   bool   `json:"isLike"`
}

type MediaPost struct {
	ID     string `json:"id"`
	Postid string `json:"postid"`
	Media  string `json:"media"`
}

type Message struct {
	ID             string `json:"id"`
	Conversationid string `json:"conversationid"`
	Senderid       string `json:"senderid"`
	Content        string `json:"content"`
	Date           string `json:"date"`
}

type NewCommentPost struct {
	Postid   string `json:"postid"`
	Userid   string `json:"userid"`
	Username string `json:"username"`
	Comment  string `json:"comment"`
}

type NewCommentReels struct {
	Reelsid  string `json:"reelsid"`
	Userid   string `json:"userid"`
	Username string `json:"username"`
	Comment  string `json:"comment"`
}

type NewConversation struct {
	Userid1 string `json:"userid1"`
	Userid2 string `json:"userid2"`
}

type NewFile struct {
	Groupid   string `json:"groupid"`
	Filename  string `json:"filename"`
	Mediaurl  string `json:"mediaurl"`
	Userid    string `json:"userid"`
	Ownername string `json:"ownername"`
	Filetype  string `json:"filetype"`
}

type NewFriend struct {
	Userid   string `json:"userid"`
	Friendid string `json:"friendid"`
}

type NewFriendRequests struct {
	Userid      string `json:"userid"`
	Requesterid string `json:"requesterid"`
}

type NewGroup struct {
	Name    string `json:"name"`
	Privacy string `json:"privacy"`
}

type NewGroupInvited struct {
	Groupid string `json:"groupid"`
	Userid  string `json:"userid"`
}

type NewGroupMember struct {
	Groupid string `json:"groupid"`
	Userid  string `json:"userid"`
	Role    string `json:"role"`
}

type NewGroupPost struct {
	Groupid   string `json:"groupid"`
	Groupname string `json:"groupname"`
	Text      string `json:"text"`
	Privacy   string `json:"privacy"`
}

type NewGroupRequestJoin struct {
	Groupid string `json:"groupid"`
	Userid  string `json:"userid"`
}

type NewLikeComment struct {
	Commentid string `json:"commentid"`
	Userid    string `json:"userid"`
	Username  string `json:"username"`
	IsLike    bool   `json:"isLike"`
}

type NewLikePost struct {
	Postid   string `json:"postid"`
	Userid   string `json:"userid"`
	Username string `json:"username"`
	IsLike   bool   `json:"isLike"`
}

type NewMediaPost struct {
	Postid string `json:"postid"`
	Media  string `json:"media"`
}

type NewMessage struct {
	Conversationid string `json:"conversationid"`
	Senderid       string `json:"senderid"`
	Content        string `json:"content"`
}

type NewNotification struct {
	Userid   string `json:"userid"`
	Username string `json:"username"`
	Text     string `json:"text"`
}

type NewPost struct {
	Userid   string `json:"userid"`
	Username string `json:"username"`
	Text     string `json:"text"`
	Privacy  string `json:"privacy"`
}

type NewReels struct {
	Userid   string `json:"userid"`
	Username string `json:"username"`
	Video    string `json:"video"`
	Text     string `json:"text"`
}

type NewReplyPost struct {
	Commentid    string `json:"commentid"`
	Userid       string `json:"userid"`
	Username     string `json:"username"`
	Replycomment string `json:"replycomment"`
}

type NewStory struct {
	Userid          string `json:"userid"`
	Username        string `json:"username"`
	Image           string `json:"image"`
	Text            string `json:"text"`
	BackgroundColor string `json:"backgroundColor"`
	Font            string `json:"font"`
}

type NewUser struct {
	Firstname  string `json:"firstname"`
	Surname    string `json:"surname"`
	Email      string `json:"email"`
	Dob        string `json:"dob"`
	Gender     string `json:"gender"`
	Password   string `json:"password"`
	Profilepic string `json:"profilepic"`
	IsActive   bool   `json:"isActive"`
}

type Notification struct {
	ID       string `json:"id"`
	Userid   string `json:"userid"`
	Username string `json:"username"`
	Text     string `json:"text"`
	Date     string `json:"date"`
	Status   string `json:"status"`
}

type Reels struct {
	ID           string `json:"id"`
	Userid       string `json:"userid"`
	Username     string `json:"username"`
	Video        string `json:"video"`
	Text         string `json:"text"`
	Date         string `json:"date"`
	Commentcount int    `json:"commentcount"`
}

type ReplyPost struct {
	ID           string `json:"id"`
	Commentid    string `json:"commentid"`
	Userid       string `json:"userid"`
	Username     string `json:"username"`
	Replycomment string `json:"replycomment"`
	Date         string `json:"date"`
}

type Story struct {
	ID              string `json:"id"`
	Userid          string `json:"userid"`
	Username        string `json:"username"`
	Image           string `json:"image"`
	Text            string `json:"text"`
	BackgroundColor string `json:"backgroundColor"`
	Font            string `json:"font"`
	Date            string `json:"date"`
}
